name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-hack
        run: cargo +stable install cargo-hack --locked
      - name: Build
        run: cargo hack build --verbose --feature-powerset
      - name: Test
        run: cargo hack test --verbose --feature-powerset
      - name: Doc
        run: cargo doc --verbose --features full
